@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CanoeCoachParser" as CanoeCoachParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant "editedTraining:Training" as Training LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> CanoeCoachParser : parseCommand("delete 1")
activate CanoeCoachParser

create DeleteCommandParser
CanoeCoachParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> CanoeCoachParser
deactivate DeleteCommandParser

CanoeCoachParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> CanoeCoachParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> CanoeCoachParser
destroy DeleteCommandParser

CanoeCoachParser --> LogicManager : d
deactivate CanoeCoachParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

create Training
DeleteCommand -> Training
activate Training

Training --> DeleteCommand
deactivate Training

DeleteCommand -> Training : removeStudent(studentToDelete)
activate Training

Training --> DeleteCommand
deactivate Training

DeleteCommand -> Model : setTraining(training, editedTraining)
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> Model : deleteStudent(studentToDelete)
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> Model : updateFilteredTrainingList()
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
