@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyCanoeCoach <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class CanoeCoach
Class ReadOnlyCanoeCoach
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Student {
Class Student
Class Id
Class Email
Class Name
Class AcademicYear
Class Phone
Class Day
Class LocalDateTime
Class UniqueStudentList
Class Attendance
}

Package Training {
Class Training
Class UniqueTrainingList
}

Package Tag {
Class Tag
}


Class HiddenOutside #FFFFFF
HiddenOutside ..> Model


CanoeCoach .up.|> ReadOnlyCanoeCoach

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" CanoeCoach
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

CanoeCoach *--> "1" UniqueStudentList
UniqueStudentList o--> "*" Student
Student *--> Id
Student *--> Name
Student *--> Phone
Student *--> Email
Student *--> AcademicYear
Student *-> "*" Attendance
Student *--> "            5" Day
Student *--> "*" Tag

Name -[hidden]right-> Phone
Phone -[hidden]right-> AcademicYear
AcademicYear -[hidden]right-> Email

CanoeCoach *-[hidden]-> "1" UniqueTrainingList
CanoeCoach *-[hidden]-> "1" UniqueTrainingList
CanoeCoach *-[hidden]-> "1" UniqueTrainingList
CanoeCoach *-[hidden]-> "1" UniqueTrainingList
CanoeCoach *--> "1 " UniqueTrainingList
UniqueTrainingList o--> "*" Training
UniqueTrainingList o-[hidden]-> "*" Training
Training ---> Student

ModelManager -->"1" Student :  filtered list
ModelManager -->"1" Training :  filtered list

@enduml
