@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface CanoeCoachStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonCanoeCoachStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> CanoeCoachStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonCanoeCoachStorage .left.|> CanoeCoachStorage
JsonCanoeCoachStorage .down.> JsonSerializableCanoeCoach
JsonSerializableCanoeCoach .right.> JsonAdaptedStudent
JsonSerializableCanoeCoach .left.> JsonAdaptedTraining
JsonAdaptedStudent .right.> JsonAdaptedTag
@enduml
