@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CanoeCoachParser" as CanoeCoachParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedCanoeCoach" as VersionedCanoeCoach MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> CanoeCoachParser : parseCommand(undo)
activate CanoeCoachParser

create UndoCommand
CanoeCoachParser -> UndoCommand
activate UndoCommand

UndoCommand --> CanoeCoachParser
deactivate UndoCommand

CanoeCoachParser --> LogicManager : u
deactivate CanoeCoachParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoCanoeCoach()
activate Model

Model -> VersionedCanoeCoach : undo()
activate VersionedCanoeCoach

VersionedCanoeCoach -> VersionedCanoeCoach :resetData(ReadOnlyCanoeCoach)
VersionedCanoeCoach --> Model :
deactivate VersionedCanoeCoach

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
